import { motion } from "framer-motion";
import { OPERATOR_NAME, EFFECTIVE_DATE, CONTACT_EMAIL } from "@/lib/constants";

export default function Privacy() {
  return (
    <div className="flex flex-col max-w-4xl mx-auto">
        <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="flex flex-col gap-4 border-b border-border pb-8 mb-8"
      >
        <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-3 py-1 text-xs font-mono border border-primary/20 w-fit">
          LEGAL DOCUMENT
        </div>
        <h1 className="text-4xl font-bold tracking-tight text-foreground">
          Privacy Policy
        </h1>
        <div className="text-sm text-muted-foreground font-mono mt-2">
          Effective Date: {EFFECTIVE_DATE}
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.4, delay: 0.1 }}
        className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-semibold prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4 prose-p:text-muted-foreground prose-li:text-muted-foreground"
      >
        <p>
          This Privacy Policy explains how {OPERATOR_NAME} ("we," "us," or "our") collects, uses, and discloses information when you interact with the Quartermaster Discord Bot and its associated infrastructure (the "Service").
        </p>

        <h2>1. Information We Collect</h2>
        <p>
          To provide operational functionality, moderation tools, and cross-platform integrations, the Service automatically collects and processes specific categories of data from Discord and interacting users.
        </p>
        
        <h3>A. Discord Data</h3>
        <ul>
          <li><strong>User Identifiers:</strong> Discord numerical User IDs, usernames, and display names.</li>
          <li><strong>Guild Identifiers:</strong> Discord numerical Guild (Server) IDs, Channel IDs, and Role IDs required to route messages and enforce permissions.</li>
          <li><strong>Interaction Data:</strong> The contents and metadata of commands executed through the Service, button clicks, modal submissions, and events or message metadata required by features explicitly configured by server administrators. The Service is not designed to collect general conversation content.</li>
        </ul>

        <h3>B. Moderation and Operational Data</h3>
        <ul>
          <li><strong>Blacklists and Audits:</strong> Records of moderation actions, including targeted user IDs, reasoning text, timestamp data, and the identity of the moderator.</li>
          <li><strong>Workflow Data:</strong> Information submitted during administrative processes (e.g., uniform approvals, payouts), which may include contextual notes or status indicators.</li>
          <li><strong>Log Files:</strong> Operational logs generated by our servers, including error traces, rate limit metrics, and backend telemetry necessary for diagnosing issues.</li>
        </ul>

        <h3>C. Third-Party Platform Data</h3>
        <ul>
          <li><strong>Roblox Data:</strong> Roblox User IDs, usernames, and asset IDs submitted via commands or fetched to facilitate integrations (e.g., verifying uniform ownership).</li>
        </ul>

        <h2>2. Purposes of Data Processing</h2>
        <p>We process the collected information for the following purposes:</p>
        <ul>
          <li><strong>Core Functionality:</strong> To execute user commands, deliver responses, manage server configurations, and automate administrative tasks.</li>
          <li><strong>Moderation:</strong> To enforce server rules, maintain operational blacklists, and provide audit trails to Guild administrators.</li>
          <li><strong>Integration Syncing:</strong> To bridge Discord operations with external platforms like Roblox, Trello, and Google Sheets according to the server's configuration.</li>
          <li><strong>Service Maintenance:</strong> To monitor system health, debug errors, analyze usage trends, and improve the reliability of the Service.</li>
        </ul>

        <h2>3. Third-Party Processing and Data Sharing</h2>
        <p>
          We do not sell your personal data. The Service acts as a conduit between Discord and other platforms configured by the Guild administrators. Data may be transmitted to or processed by the following third parties, subject to their respective privacy policies:
        </p>
        <ul>
          <li><strong>Discord:</strong> For receiving interactions and sending responses.</li>
          <li><strong>Roblox:</strong> For validating assets and user identifiers via public APIs.</li>
          <li><strong>Trello (Atlassian):</strong> For syncing operational tracking boards and manual blacklists, if configured.</li>
          <li><strong>Google Sheets:</strong> For logging administrative actions and payouts, if configured.</li>
          <li><strong>Replit:</strong> Our infrastructure hosting provider, where the Service runs and service data and operational logs may be processed.</li>
        </ul>
        <p>
          <strong>Disclaimer of Affiliation:</strong> {OPERATOR_NAME} is an independent entity and is not affiliated with, supported by, or endorsed by Discord Inc. or Roblox Corporation.
        </p>

        <h2>4. Data Retention</h2>
        <p>
          Retention depends on the data category, the configuration selected by Guild administrators, operational needs, and applicable legal requirements. We aim to avoid retaining data longer than reasonably necessary for these purposes.
        </p>
        <ul>
          <li><strong>Configuration Data:</strong> May be retained while the Service remains configured for the Guild and for a reasonable period afterward for recovery or administration.</li>
          <li><strong>Moderation Records:</strong> May be retained as part of the Guild's operational history until removed through available administrative processes, the connected service, or a valid request.</li>
          <li><strong>Operational Logs:</strong> Telemetry and error logs may be retained and rotated according to infrastructure, security, and troubleshooting needs.</li>
        </ul>

        <h2>5. Access and Control</h2>
        <p>
          Guild administrators retain control over the Service's configuration within their server. Administrators can manage role permissions, clear specific database records (where commands permit), and sever the Service's access by kicking the bot from the Guild. Users seeking to remove specific moderation records must contact the administrators of the relevant Guild, as the Service acts as a data processor for that Guild.
        </p>

        <h2>6. Security</h2>
        <p>
          We employ commercially reasonable technical measures to protect data from unauthorized access or destruction. However, no digital transmission or storage system can be guaranteed to be entirely secure. We cannot make absolute claims regarding the complete security or invulnerability of the data we process.
        </p>

        <h2>7. International Processing</h2>
        <p>
          Data processed by the Service may be transferred to, stored, and processed in the United States or other jurisdictions where our hosting providers operate. By using the Service, you acknowledge the transfer of information to these facilities.
        </p>

        <h2>8. Minors</h2>
        <p>
          The Service is not directed toward individuals under the age of 13. We do not knowingly collect personal information directly from children. If we become aware that we have inadvertently collected personal data from a child under 13 without verifiable parental consent, we will take steps to remove that data.
        </p>

        <h2>9. User Rights and Contact</h2>
        <p>
          Depending on your jurisdiction, you may have rights to request access to, correction of, or deletion of your personal data. Because we process data largely on behalf of specific Discord Guilds, we may direct your request to the respective Guild administrators. 
        </p>
        <p>
          For privacy-related inquiries, please contact us at:
        </p>
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="font-mono bg-secondary/50 px-3 py-2 rounded-sm border border-border inline-block no-underline hover:border-primary hover:text-primary transition-colors"
          data-testid="link-privacy-contact"
        >
          {CONTACT_EMAIL}
        </a>

        <h2>10. Changes to this Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. When material changes are made, we will update the "Effective Date" at the top of this document. Continued interaction with the Service implies acknowledgment of the updated Privacy Policy.
        </p>
      </motion.div>
    </div>
  );
}
